services:
  db:
    image: mariadb
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    depends_on:
      - db
